### ISSUE TITLE
1.75 fn, non deep dish f and j, and possible alternate layout?

### ISSUE THREAD

**Issue by rjmana** [jasonm23/ristretto-affogato-keycaps#10]
Hi! Great work. Please consider the following:
1. Non deep dish F and J as an option included in the base set like other sets do
2. More alt mods:

2a. Adding a 1.75u "fn" (some poker 2 and 3 users go with the fn mapped to caps lock).

2b. A short shift (1.75u - useful on compact 75% layouts like this http://ortholinearkeyboards.com/top-plates/neutrino-top-plate and this http://winkeyless.kr/product/b-mini-x2-pcb/) 

2c. Extra left shift (2.25u for fc660m users)

3 . Lastly, consider the possibility of an alternate set of modifiers matching the color of the alphas (starting light and getting darker to the bottom)? somewhat like this https://www1.massdrop.com/buy/tai-hao-sunshine-pbt-keycaps?mode=guest_open - it's something i'd definitely buy in addition to the standard set but not sure if it's something a majority would be into

Thank you for hearing me out. Love this design

edited to combine alt mods

**Comment by jasonm23** [comment]
Closing this and splitting to individual issues

**Comment by jasonm23** [comment]
Migrated to #11, #12 and #13
