### ISSUE TITLE
Alternate set of modifiers matching the color of the alphas

### ISSUE THREAD

**Issue by jasonm23** [jasonm23/ristretto-affogato-keycaps#13]
Lastly, consider the possibility of an alternate set of modifiers matching the color of the alphas (starting light and getting darker to the bottom)? somewhat like this https://www1.massdrop.com/buy/tai-hao-sunshine-pbt-keycaps?mode=guest_open - it's something i'd definitely buy in addition to the standard set but not sure if it's something a majority would be into

**Comment by jasonm23** [comment]
I think this another child deal, I'll put it together and see if it will be ok to produce.

**Comment by rjmana** [comment]
awesome. it all depends on the interest check i guess.

**Comment by jasonm23** [comment]
Depends on how I get it produced.  Livingspeedbump is very generously going to assist in kicking off the GB, I will bow to his greater knowledge of production if it comes to it.

I would really like to be able to offer a set of kits as varied and comprehensive as the [Round5a](http://deskthority.net/wiki/Round_5a) sets (I dropped about $400 on that... my wallet is now in recovery mode!)

**Comment by jasonm23** [comment]
Done
