### ISSUE TITLE
Filco MiniLa Set

### ISSUE THREAD

**Issue by Hanahlol** [jasonm23/ristretto-affogato-keycaps#9]
- [x] 1.75u caps lock - R4
- [x] 1.75u ctrl - R4
- [x] 1.75u ctrl - R3
- [x] 2u shift - R4
- [x] 1u shift - R4
- [x] 1u delete - R4
- [x] 1.5u backspace - R2

**Comment by jasonm23** [comment]
Thank you

**Comment by jasonm23** [comment]
3u space as well. (currently in the space bars kit)

**Comment by jasonm23** [comment]
~~note: 1.75u ctrl will have to come from the alt control kit~~

**Comment by jasonm23** [comment]
Figure it's better to have that single cap in the planck/small form kit too.
